language: node_js
sudo: required
node_js:
- 8.11.3
env:
  matrix:
  - CXX=g++-4.8
  global:
  - secure: NAEBhTHZ2l4hcO1RUcaHnT8kjD1+l1WVFirugSjY3fIBO0y4+78RZmmQzGXpgp/0tZixKMuLuSHfboVBBMMYLchjF4kL+AVQCgcYEMXm/nYLBtcN/qVBOe7DfdL3MBQ7FVLXCahtKhTIRRO4Fn4IMAzj+KZE6uqLfcD+Mr9ZDJTvzLQE0+2jSUwd2HoXYWFIH5Dzivqpw+0XZZJWSh7WljKF2Vzgpsk7c2X0H8Mg03XBFbocodeyrzD4/HoaoGrUxYy8bridoIx039RXqFCvOd9nl2kgL6Em6TazYva/+QDMo6+nur2/kxCGxZt5kAkvBc0JLX5C96Y8KJLxRzbD828tn3KY0MHAfJvolbEEAYf2mibQ6repQfeptWpOmES57HFXjLdC9KIKiuulWxvaqKnwPgG+c1aDbb/kYmutAm5YAoU0VGCDNKMtffMLdQmciLexsAuNwhgXdaszlw/s3WQ+8kRcLqh9jzvxwd4gyhPfRkSDu1EX3r6zJ+FXlJ5cGnzAQ17/UgBDYOZDUV4KfewzSj9VkHlLBF/jrg4ADbemGD61uixDzvTr1oMIrZp2Jpz882rbNJC22yEpsImSASNS1as5wq2/wdHZRAGNvV7mPm36oDQ357tgqWbJQ8QfwZdajKhhFTVNEeSJ9hmjISI3CNu+NzviF9gyzB4g3Qc=
  - secure: n0Bxq+YEnPgJbaKSyx7VqBOdF3hdxoUuZ455huTV2hrVzadnq8nCFg38D0KYxd1fEqG2QnehPGYMnQc7Ar7fv07XuAAC8hXCC0HwerDOI1+bmrMfzFpAA4WM2GjESJPSF+Ff9emRse54hrrJ0Oul4iOPX47BQFiOuOqDJc3npiH2BnvxstCIgzoIZitDQlBuLtlpccCUnJOpKMwG36Kqw3CN3KNRduv3xJmAbcd/H/r6oBD5fX5j5T0owm2IwVG8XAh/9+6T0h62YbGDVvubu03KyLTvLOpVA2WejpbwswoCjseUkYoPxFRxQLTA0caJhBLE42Mv5LtrqSVm+WSleO57K9VZmw97J76KYBxaI06c98r63yH15M66k7M5D56/t+omCSZmymj7UBtWUkyfHK7hZ91ZWSlaAqK8QjqgSN05LRsWzl1viXXyOU83dC41Y3KARIc1ZQhDZgkeK9H+Ol9QdaeDyZ1LubXRR++/CMmJozUb5+I68iTE8uKpCp9xgRMNEBqGVTHwbKx8gwqLYw3ELU1oSF59oUC5aUqLagR0wUhFerEl0PrbA/xl1E79MSBky4sw5aBY31dtu0tchr6WqhYBCO1YBgRDx+qKNNgkspf3NqHGPozuKRp2r5ndSLRmzuGyeeQzNKJSJcvAN8WfMCYTshwMwgi/KaE2aDk=
  - secure: E937jB1ggjFhQsfND9BrQFlWOr/eZ+sxgNtygWC6HC0bLO4iYZlbxSqt3tHofSuxtrvJITgBmOApJpeoxAZ6sfrxGnamlMyFxHM9KG5ib7uk2FtaVgeslWbqQK7IkuHFTbTuY3KhxQlerhLT5p9sIteR/0p21t+te1FR/olhp0dHlt6c4FR9vmxN64CS/GyBRYpvGkhfNqUDdx7+x+ArsquBAXCBZzhMKyl5VLhdwpQqgAREIZucizXrxhBwj9zrlZrCbS7Jk0iNSEuB0BSgblL6k+7PpeZr7UPDyyeEen08G3AlRwGYlcVr0JpvU9N3Eod1qISvjRnmz3ZQNzSixiedNT5Ct9gZSaK46kddqPEs+h78ZCNb8Fd70K2LmOAtQJvom1iAlCJ5u4YjQv5OXWneq+QfyvxmJnwER43Xp0U1LKn+PFywjz45J1tnTXhsrAPS975Akr3v1f0uRnbmUe/c0lI8ZSXVrH0UFtDMRMoQKMvdlgLesHxqlLsZG3rpQSnxw4izyZB7x3PHew/mcZ9AhYK5MUGV3myqkkr5c12d9dVTTeDz5AAEmG7Ak9WzTZblS8y1LpXNpEzM/Ejph1c3N5GTipva8IJPmc6HUsAieSh0IYwp2sHi1vZ2O2+pWc6M49LMn8/NawNLmxdMQacHtP6IOjX2MlFwdnXHXZc=
  - secure: C2HWwBfBb5QuOeu9/6xZh/sngWRqByNds/P0CHpr2D7U0WH1F7n3cUSyZMXtAYl0WFnWpA6o61j23TR2wPlVDVaYhxkJlIHgPjwIShEh+uotSve7oIjXjvBEJ4v+bTXNkF6mZ1/WJNqLr7EVlgTfJM6dA3Goohul8LmCML/BoCiDbjIq/NKcGvCGNEvgx9023rS1WdoMHhh5nQnKkLhkIG2wdoNFoejTz2jeXWSsEtS8h3tHXIgpw3cH+nNsGsDJijeJCiuuvCBEn4fRSjEIuYcxJ7FTzGqjI8BjiUdVKLrcJoYp5wwTruQW6TlVqKB1fF1S+CXmDoxEaW+3OHa+wdVow4IO+BVc32YowOaQM1UZVG3asEaGtlABLthuwGcssWU+5sARf3v1N3r6mhVw1SkD7wkP0x4Y4KJDvJ9C6k4vkVPXW+aaUI6LKHyCbyQeVUoJ3O4b40xe1sLvumAcrmIQMfZP1i0ij2YvtI/hcTBqH4ezMzvsn0+Oo1CXLnoz0yOp8zdsedZud1/+N4P7/IrFXSfbDP9tbIkufi9GuGn58QYW51uyeR5CaARwH/+79Ik9uzzMih6FTZYZN0zKcd6bU12Bt4CVjG6eWdV215T4re/UOqYhskTPBs1qx0K7TD+g7DYOzJmqLW8k8S6zirI1zD915elf07G700ZaaTw=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - g++-4.8
before_install:
- export CXX="g++-4.8"
- npm install -g npm@latest
- npm install -g ganache-cli truffle
- npm install -g @cleanunicorn/mythos
install:
- npm install
- npm install truffle-hdwallet-provider
script:
- ganache-cli &
- truffle test
- mythos analyze contracts/BluzelleESR.sol BluzelleESR --mythxEthAddress=$MYTHX_ETH_ADDRESS
  --mythxPassword=$MYTHX_PASSWORD
- truffle compile
- truffle exec scripts/deploy_test.js --network ropsten
