language: node_js
sudo: required
node_js:
- 8.11.3
env:
  matrix:
  - CXX=g++-4.8
  global:
  - secure: T0urwPkfYjreO/JCq8WmMHqGuSg2fcZdlXS4ZtBVztcnFzB4bJcu3Q8Y3xSAAbrGJ6VJPLheWJ/0Tby6Sk09gvHnFvIOKHPaL0ix62lfYPVs2h3EpDyQKWHdkxR97B9NV4pqQKAEsQz5zmrEHvewDddRS5QsNwAXCsULystwal56d1brEV/81kTnfYNdeAOG/460dU1YOWRfM/fHMYvijQncYEr5l72ZS+bQeNlS8eR8YWJ2q2zgTLCRTSEA7yC5ePRB3QNvhTribCJH1oDsDLIKpdTClIo7usORQneA1J4XfwTLyDD9EQ0FLXLVhjN5/kqv4d0P50Aq+49X2/+kCyBS/VVe6rnvKPXrSRR1SFa+pyUfCnIO222/jVRrPlKRyn9GTR+pq+hsya8BCot8YsnPAdD9bzxweBfzXzHRc50m3B8cTTnAoDtphUfjnZo+Gk86M+KFR2KlSJmtVpQK4+AoSFFM5Bqp66cFF0CHNC8Hqo1UkLYL0cAzFj0E5sTqpuDtOS6Uc8SgrQqbnDei9WmyfNbwezRDdh0YSLlHkox4tS8vJxYnWFlcFSKydhwr2C+5KXPiVjNJ6FMUqzCZtdVio/Q0wqroWbPYj4xuiwtCL857TN3LetAspTH7v5THnLjANOmKML+jts1X205+rmze0o0loVn9HqwdzLR2nho=
  - secure: VQgjMCizdX5vRZIvQdMLXGdNYzh+TThg7lxhxe0y6dmEs83yjBmlRkQm71bLTFXtoTCrfgrogjX8SwmiKINCOOXFJkr5lsMMak4VT72ncKjPx9DTfSJjVj3MxFAWKQze0gnQ8XX5h2wZcVv6C3EDV9g7NXBuFuB39uTqDEohwIP2kPQbe38/44oEuh8oHBi0kxDGRxRBBFO56O/IQn8M8M7DdUveOwVED6i5jI8uct5R/2n7rDogD4fMUgoNYRbX6ilA5fXA+/2hkL3932GTz8c/kLmSqm40GNxTEQREai0Ns8VtVWzJV5chn66cRd8iU/XPGv5tL3kedydXR8FqyA9g/LUwngk75ipwv7e3HbbYyfks6Tu8LB/srAW7KgQHIqsGOQnRPymIJiL0dy1HXe/5pBV7YX7VTr/CsvIFxVmMqGZBA3xQd/H3duf8ogs4CCETV4/vjjQiDsIEk++ML3l/uQmoTYUE+mcgCXpaev1ZyBex0+JzG6Ax0hUmE8uQH8+5aLe4vQ+RJqpjZajh9RyD4UNF91yvv72krK55E0VtSLZ9DA+ZkU7zSVWwZ53yb7HmmLz65SukitvzMSx+vp2krxt7x9KveWDACYYbxutW34q2JPL/0WZRFSEDxCebMvNTCzuGber7MXqCTbWycRslTDtyP7TsRmTAvipkSiA=
  - secure: dNdUss2p8z5yKHJRVXNguI/Eufm7R02ip7PeIBy6Wg7YCPLyIlJ6g1egBJA/MkBc/uT8hlFTrZ+IOx1H6zgCF0J/bhC51gkVxconL/I0CTwi779gRHIEaaqLfjd2uLVt1qndFN96633Ev78LZV8iWIquNENfcRIn1ZyXsXyA8qCY52ETu07vkEE1SiLJyjdI5e63JgePD7MCr0AurtB7a3dI7VDk1eVzNP72/5RmfVuE1pYmyrvfOATX80mud3VAT9Z7okjdrSvkZ9aN0AobtV5PfZ4b0dTjMB0WQL8d78IQ7jeKuICi7UmvXyPpluQPNSJ/fTZ0TP9FwIpgLw0+8HscP4jxaehhIf9V/e/td8KDhQtia8QUkBtAhMI28WpF4sWidcRCGzO9oAq5Roej2wwSughenGMr46rdgxN5KY31z/LKefZ2orPEGvEk6yX/UzgjkzFFLmh1XxocA3WVR+PlXnHOBv/hjrsJIxrLM6+wqKwWYZZQZaCEvm+shQoUwwmBCYs95SlWIdGD5kXbp/djs1qBaFsiSDCpTeC9sIhtxuwPkWktw+2Yh0AiS6KjXJ3nB3M9hgfJRHEfVgAQ6G2K6TDAmhZebD3x6MPJ1WpLykYduaHK7YbTtTDbCZrGpU5H8bxKHUG8LQvdzYa79BSeRZo2OL4Yo8SnwfuJl4c=
  - secure: YDSvCvVbclhKyga5BKSgAWutmzO8pnIabEyLMPYmH2ax7x0Qop3GpICuM3LVlPGq6DYan0wpj00tGR7BRi9XmbzIMJLaDOz+vjx7c+Kr3798j3s6aFSi7iQpAWbKEnXnEm0oBI+2QpLt3stLubfbLZK7RpqowsHSeOliqzFztJOTD30IPqoVigP8FRlKjrnWtJNs2hl/Y+YIoIDOUCD7ZTIAYyaivAGNNyMb0c+ntmtrYj+hBaNT27xCUr5uSkkY/mWVhJDOeg5AmS4tyMm8oJ6NPWQPP2bYAp83qf1J5pUXgw4PUB1Bc4IHWLNVU0zOJdeJPMPGOE34j+nzLxbyQqly1C3HLSoODknwSEjG6ql5sPrfPJ8A021T96XxPBSfHojblsu5fKWcDhoJ28Mk9OPJ7mCpTlb4Bn+dB0mPIHDAQvCiSiLSrytYv+u7E72uucc5Lq/0ISseYelQFGlumYsG6qn3cywlLn/V8+KoVLzEGKHhlaIAl/EDHEMgBHh2jUHrY5Iu8effj4trh7fYtgFid+zdvu0f72LsEB/CV7OxzAkdjUTjG+gXzLqDLochgzSAZ6pt9e9MMxYlpzUwBZU+60+UZTOeMQolHAlD+X22TJ2acyCcan7LtsZhYvXduHW8XcVFsTrjux48AN+3K41YbbBMXnpnm5fa5LOGy4s=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - g++-4.8
before_install:
- export CXX="g++-4.8"
- npm install -g npm@latest
- npm install -g ganache-cli truffle
- npm install -g @cleanunicorn/mythos
install:
- npm install
- npm install truffle-hdwallet-provider
script:
- ganache-cli &
- truffle test
- mythos analyze contracts/BluzelleESR.sol BluzelleESR --mythxEthAddress=$MYTHX_ETH_ADDRESS
  --mythxPassword=$MYTHX_PASSWORD
- truffle compile
- truffle exec scripts/deploy_test.js --network ropsten
