language: node_js
sudo: required
node_js:
- 8.11.3
env:
  matrix:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - g++-4.8
before_install:
- export CXX="g++-4.8"
- npm install -g npm@latest
- npm install -g ganache-cli truffle
- npm install -g @cleanunicorn/mythos
install:
- npm install
script:
- ganache-cli &
- truffle test
- mythos analyze contracts/BluzelleESR.sol BluzelleESR --mythxEthAddress=$MYTHX_ETH_ADDRESS
  --mythxPassword=$MYTHX_PASSWORD
- truffle compile
deploy:
  skip_cleanup: true
  provider: script
  script: truffle exec scripts/deploy_test.js --network ropsten
  on:
    branch: master