language: node_js
sudo: required
node_js:
- 8.11.3
env:
  matrix:
  - CXX=g++-4.8
  global:
  - secure: pJAQGLCVq543DHKTWJW+OJfqzGLGbDRUWipTbLsOKPHDVC2tntD2k8IwduGAemB5Swz/u9ALeTXyUyWLX1ATqJpgl5jEQ289wE2tQmIKW1CmQ/HeJnfA7DmWYkunqzQOe3ofEE767AfFSjUnYivoH17VY2kgkHqZfPp91cKt473V9AkStey51/qySC1ov13AlnuAKeqADTuwVfx4lG0a5fbdu+nlM8I8kBXNHh+HGjWsBHnmPnk+m3kSgrZcu6pRZILAmKCz+RCnH1mSw89P6aSc6ghnjlwMyBVYmhYjuLJwm4t92gxulm2MBzWyAZUURoWm2Y6+6W4zJ9ixhDh5jhc4kLD0QV46xdHRyDAsie7eqIfzvoQGHF/9QZTyCqEsHCQzoKi4EGvDfMzj/TOP+88IyvysPolOI0nvxkUPur7id8TtjLDK3RnUSMsOyOA6fo0CZWuX7rsiC/fqqguQWki7ccLpFhbN8NheZquMaEqe/UB4cwZS9wkWNvV0IAgXRI1QlvO2ExUFUypumqDhK1VW/y5VTKDkPSKc21G6dcwlcVDwFGNM4oJbzNQbSu6KiDYZsvp2KMMIJPbnv7eV4fQ92Bn5cD6dS75C+++SL1JOe4ejAkPn82TkQ2tYmwvc5TZSd6V40XFMwketn6UtNSGv4CPCN7Uhk1PFHrkzDA0=
  - secure: r7LDcndaqV8d3BDiQQSTyizq/3d+jB3tnixmjm7XPz1wGLHyZGyzsuFisZ090G0N/Ye4y5whF3VS5+wGnz5ijjsU1ihzh6P4541Lqzs9g+fiuTe7A+vEGsKBsrO1zGijv+c26Ygwz47/Ye1XhgFjgoXpsjxbkOeDWvR8RjG2BTcp77hvj6Ray5uoWbMg56ZZMmXHInF6voTRx5/cX2WL4J6Lia2EunBopAS/RpJxuBijKntA4em8zcsmFyqMbGJhgivgcBsYI2BbuaWTVA0KfoC+OPu6ogESpo9U6K6zHtKWO6VvL8hRcTMcyT7hEg2gvGtEsXGRRBPSNl8FrT1R/UXOsRHT6IMoHD/Efozob38uHJzFwkKi6ilx57S2+W5m9UlpNDs8mIuCCCQvZV5Y6oMaHwgvrmrc6Q5AjpplpShtB0j6HueQFLM1vyFXHlsDkXrvspC45f36BHaKIs15LZLv9lLTKMu9tDnnknIoglC5qNI838MyAUc+VBnMYBc3+TXAOexvD0aH6uzoSwCMAp3F2Ravusk8EG9eh2Sz14HKhdYpwBbQtwu8kPXdOz+9FPLq1FdMXp12iryQnv21FvayudQYWT/fY0kgz85QQ3k//KfaXLk1uTQs++6KYfaxvgPmcaMQuGW2c+Lefsvh6CW7OueCwzsgV6nKvoCQBzg=
  - secure: 0KFoxipAElFC846jbZ/SYZpCL2gAjYO64961qYe/Hm6+K6N03XeYwsX7wi9B+FvWvz+nm7jBh0Z+S0O5av74JSfsKEH7bCf/5wicukz+87ca/yZjdtX+8DS/RPKUBwi97+NR43h2LTnZs48zakG5AEkN5Xnx4MQXtsJR8YQ5IK32JV28RAT3GU1BQ/I2KGPhMLeCkMRcTifvV4p2khPbRER9xNPPZs4H5FrVXR7yTYRdYQjaqvx7knxIQiJN81S2f2rI0y0EET3lVDu8a8gwJInF3JfuqakN4wQNnA2PronUtK248pXqlF9/wwpHoCr/jDA49FQZkHtXZFBOEgMUDqZ9W+FLCVmQk9q1dUyOnqMa4Hj2uUJcmY6ZIPNvrgMSGSbaIU1nVkN0N8/STzFlwqx1NLtNawyPyY7uG4C0FqLudfyd4ow9AicmdthBVPi5FY7LwvUOnMXRbR7CY0kcpUVdAlBpquYjHm0IR/CQAmjb3a3H1SoN9cX/4V3JVWDfPYMkxWkuIzkIwwQqpKhh9GkSPZCYV0LrT2tG5aufi1LfT/UAR2WTBImDl2VmY4WuHYFcm+y0loq0ghdlYIE6zxysFS4U3715B1r9T5a545t8OHTAOsVubI4EEV8qzSul7VE7rhvulWcAfmh8kifB8r92n+PVeCNrbnl+KS4xqSo=
  - secure: vzXNRjfZ9NnFHXwJ7ug5THunnhFv/wuDCT2Z1gxIXsldsk+T1ArjHzB68i+PAYKtya24a1MjaFqTaq0tDTGt1ZlXh4oitnf72bHVL3oWMQqnCfUu+z2QDs6bNAGx46vRO6Av2GgW69lVCoEaV2d58UMUKRHuiSjX0iM+DTaNgpnFxTcMqXEP033Uyxr49CCMJ4jjL8rEW/VlcbP0ipodEfvusnxEbJLpWa6PdVup8xfvJ8xrLkNIKOQXy1ylPXR1MBGAVqCu7N/oUIQILyPMoy4lhDW8UKZwaGzHiOBIQBONzu9qoGn9A7GHFrkti/qrUZjqKdyVJSrN1EuC3bUKd95Olr3l5yluFbtc5gHNdbDsrPSLfh5aqOO2Og42p/hM2tyAInfvNfedQkbQ1N3lBBJ6p11mb16i4FZehSe9Mb9BX/KSAmYWYWptDboEE85qgtsJUevUDlygibpWcxhKMFoTI+Rf9u5pD+1iE168zlkeFvaqOBH6fVTL7JctTNhdeU2mpQii1I45PATA/+B1C48DGZIR9tamBl+R/JpcB4vntEUjR+XXndvp4/0NpkHNB7IM/pJU6J74c48sJWh1L2QokVxS4mt5dI9CP1kjNcI0PZvlHp6OHBADu++T4BFt8ZGgmMDbdGVZp5PjSkGE3O92plB7Lm8Ituovhnl2Zsk=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - g++-4.8
before_install:
- export CXX="g++-4.8"
- npm install -g npm@latest
- npm install -g ganache-cli truffle
- npm install -g @cleanunicorn/mythos
install:
- npm install
- npm install truffle-hdwallet-provider
script:
- ganache-cli &
- truffle test
- mythos analyze contracts/BluzelleESR.sol BluzelleESR --mythxEthAddress=$MYTHX_ETH_ADDRESS
  --mythxPassword=$MYTHX_PASSWORD
- truffle compile
- truffle exec scripts/deploy_test.js --network ropsten
