language: node_js
sudo: required
node_js:
- 8.11.3
env:
  matrix:
  - CXX=g++-4.8
  global:
  - secure: bKXtpmwlTbWoHHY683yovu5+MsXmV2/yo/7WbQA3lQgLUKUQe52hN8j+2P37jMUDkl6ExPiJwEWM/XxGJxRcH+pQ2qgWlRAF1KAAaLe2bAhrj3qe7NUtVnY17/0GjKQqdfMW8hgSjQ2QPktM2ItkVeSt+Pe63PcKFwBzWwiRz6TP5Sr6PxStRd0XoZzMhiuzRyywR/Zc8f3bgwvseOomsy4JIRHGTQ2bPN9qDku3bCD8yjouGk4PmJ0ErH4aKPYlKOTmdYls9s1hsQg641bahLWVrzdnAlk2ll9evOhF5QUPXDgPMkpkwi/Jifq0JeWFhvepwuRh25byk+lRlrS/1QsH8ZhedESnY8alRfz4kIaVnIvho20Pw6kUyqpAu2wOFI1Nhp2vYJzIp1Xrv6pl7Om1OTzTh+kiMYkipYA5qd3ts5cyvE7txz+zabQ+WFvGImF8uftYWddv6Gq+Q+OClBlvsjf+fCP4c9XVpqIhytkSpy2JY6n9fxXa2DThYhzRryR4RMuGQKuntZFY2A6bu3flO+JDMFgkjcaQy3heO4Iv9V7Y+PbaOSkK+A8TG88Be+bhcJAg0/6uvcuPpVk9fZUcw98KMchdDpx5iBxRMBGQ1vlUoM1IAQSzSQyisjbfXXW1pFYQZpTPKR1uBese5l72qXwPOTNtDbknzLv6xTo=
  - secure: S2HDDlgGEEVUAeEOcFcyol8EPQ4l9y2UOEiwll4Ut+eQnpXIwjeiKTJRwywSUimCjCcnrV18iLkTmL5d0nzs1iMoqgbmgj+qBR1YggRUM+wBT0M1sHc1GPxxYVIooOssJOeyRRfh9M8642TYYZs5rIO7qovIshE3/t0XNOOVVF9l6B1V3WDzP/tDccPnyQzt/4BFgmsLyMRcSBi/p6pLbxqoGlXV1j2pA2T+W0E316ooxKlRMb3Y/NDkmnnawtCdxP5XfAkmc/1eU3kBuFjZM6cYVOi+kctfklt0hNW8Y8vdTbcE0iqYDMcWTbyYqQ8MyEts6cgfNKZworsK1BwozwuvQgZ3Kx/wxnXlgqL16i9uGg/lfN8SZFE4wq8asPXiAGiylNBd7pf9WJtguWT1k+1KSLSXvtX2L1lyEv8DyD9udpmex4ZSoz3qFyy7dVoO7YJZWoSj/yQsgYEZLMHtPLVUujkT1m0M+uCaTWFNsFjBRrLvHgewV+A+EIGYS5uqNpfvR442VhvvD6piH5FW/l0Vf7VDhe4LhtQIr+tFqNS57jLXKoXNS5+IEPcmr6obxsH+7Ti4LJBXGjzg/V8afbX+FNx3kA2nwh8IGIEPhrNaj/BPTH5VWoABNAFjusSOEJjaS8gHtf/cUCwi7h4Xism9Xi9gQrDKe+ijIwo/p/Q=
  - secure: cPJrkcLqbS3KlQnputexpZVV0pzjGs/JbSbhXOtEj61J1UfglKsLDIFMiXMX3pXJNKHDDYip7pyximegC+ISia5UP17A0wq0+wikZMvEQfwk4jbe9NFAdc0qaCurv7YhvM0Pdq/+Sx+88PPnk3qQQYN8PhDOP1HhJ87Mz0yxYJyvfJiTRWGqNX7FsjwUj14vk/ZfvEGc1pFyMNMBJ9nEFRwOUNJ+ovBO4wGqV1lGA/HGXxd5/5FvXfC6EW8HfJEG5LxqABY+AuYQZMDKR+Ab87jiSL8RM03PGZth5pO9vTH70cqviy0w4J6zJjRWuF5EkxLWH+TyhYCl0XkyPd+D8cd865Oa1Hd00oe3+/Sb39HGQSvZi1QPezWeKu8lE5nQ+zMGpWpG8FT75dgUFCmCfdy3IoLbRc5eg4HvBe4xkw84dn8kRu6P2bAj69JPLwtlUQNQXmpQsg6daLpdzp+VdIpAzsCrb5iEHF1oYU7n6pooe79+bNIeRfQwdjck+8JRB61zVC1bGknDn+7bqLJiAD1IrG7qqqFdc0KAf8J5IhssoMEOwxWNTDBgiMVl9Oi+ZH3gJTu53IZMht691vnurlPcA6hOyBpbov/u/2cNjfv/eFI0Ti4y8a28J32dKbu1ShHZGveNyWgeM+U8CA3nJsvf27sEbEJHSrTDliY4fQo=
  - secure: GhdWZqciwj6JEJk/e2kUCd28nALYD2QM6sqpyUE1Hf+waCcnueIymdfRprQbdRCNyERLlXCkzWFARgwXN+shcYRxaz7BfpwvYvUB6CkSM5QPYdGNONZDUjdgapVMOx9do8J46XKNOOJNsIC8/E64cWOIrd4VV8wUE5aetUmZt8XhEQ7SlGJDiR1mc6k8iytQmyA+HI4cRHuMqFS/bJT4w2p6EvE39JnOKtR2ILkVieG7qWOkDDkY/6e870/9Z2htE+bMMA57FG2auadXGU01XbSKv1is66j8mPlNNt1F/rnZzMEZ853GtDKORD94sHcHvrljZIoUkc/RZjJqRV7K9WLIzfmapyRRwshzDv9d2cAgBEHkolbs38BwzzIFB45gNEfvP4o+FxBmY35sFShlCtovv2n2SE9HywVoFBCtymR6J+isk11JPaLs1wJkUxX9B8RwDmoGSfwT8ZVYv2cAMd3CGwgtbiwSF472YjWWq8wXz4nlmD0GjCy4sbKve55IQM1BqCMTvxLCSi7mZtFsUDUrqn5JAKnppJSmJCjdIOCMajhmIRdqgsWILq6+1OoagjxlVsXaVs8M+6D4t/J/OFgJd8hWzqmhCM5iOxdw4kkTu4hsO+yhGIqCORS36LekjSCDxsKBUqle18KGt8pggwdEKIUa6yZ2vcdr6RkN+K4=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - g++-4.8
before_install:
- export CXX="g++-4.8"
- npm install -g npm@latest
- npm install -g ganache-cli truffle
- npm install -g @cleanunicorn/mythos
install:
- npm install
- npm install truffle-hdwallet-provider
script:
- ganache-cli &
- truffle test
- mythos analyze contracts/BluzelleESR.sol BluzelleESR --mythxEthAddress=$MYTHX_ETH_ADDRESS
  --mythxPassword=$MYTHX_PASSWORD
- truffle compile
- truffle exec scripts/deploy_test.js --network ropsten
