language: node_js
sudo: required
node_js:
- 8.11.3
env:
  matrix:
  - CXX=g++-4.8
  global:
  - secure: peX8m6Q8g62CZfdw7hDnjvnKmeWanNE8DDtDCL5x5LivQVtsTWzxRi6tz1AUXyx9CCImCTYLH2jmBCbUCa7jbaVgcPuicmG+rRUrIrNjqtJV0V9u8MBJaVyD4uX8GfpkhX/eqdU3hV/ZAlAldOs/A8wbca/K1prLrQz/1pTQ4Jfdyxn884HM5Zpv9TxBCwy5KzMfIpZMrDPqqcZa1bEvjSFNltbZlWs9m7W7Mm3y/YQb9/6wLxdcrhflAuU2XLJamvqBjcplgAtwC2D0QTirKV8ZwjTE+haxXSFsIzBjP2CQ0GjPcdg7Hse2eHAtn6qHtHfA16EVm2eqO3fTjlqM8SapUvcQhUHrkMwPdUa+7UXC6bxnLA+TzxBdonKl3ubBRGQwfEZEdNYhbYxxpYCiWvIxIqyVrbs2fPvkNi44kGpj13GicIfcQuBncFlgwJrn6KbgcBH2ZQ07UnMwxiM7ADESZU3JvqL+ZCohFprvHy1SVV6GiEeXfpT2ZJRbe0GLMeyOOsK4tsThAh19ISuDFy9qGwHjPVuTO/4IAFdfCazo/Wcz1Jl6FVE0C7ZS/Tqfhc6zOhnpQRJy7dk7//3bec0k+l4jzVf5BQLO0jr/Hd/ZaE4cUt/6cSDtdseUPxGvb1ABeMYmo5FyYhkOxhlH0ytECIOZQzCLowSZp4GQL40=
  - secure: ZM1aXKg/NVUCuj9pHsMnPLTbMILnDVvmjzKEQUQDIGt1hptbLL0R+NTPXYYyR2QzR8CyPzpfFPWvoAEieFFITrKOuCr70HGkeSm312G9cKEImUbP1Sgw5S7Ooav+GnGh46f5o3Ob9K+BMY2qOewv3bmYeyYWV0DP+43Jn/wbe49aYK/36Nt4Nh3bF/fXbR1mt7oLXQ5eAUQN+mOHw1t6KhNDQunLrWif73X7RtIl+K8u+e4vIqpZal9U1XKyKSlElZ7X0p9gUc/YXaPkTcBXwSwFqmmuFae1Qsl3cYotT9PwCnguUYwDZ/+VJ3+cStc0gLGvYXqeNNh7x7Pwhi00+BiM4CVysSfNNo+kB9Ajzgb93LcZ3vta4RztI0PR7Y1lDk7wbH1Z1B0THrtVvaYpicU4Ie8kjArswm62lb2bNWXEhwZ9R/6AZfljuyyGeS1S3vXg7OM6qTJyzC2e+n/9kXgS3/zKEEyKvULMREcTs0on4KemS/aW9x3bcPwd30MT5zeM2uh4N0+Fz3uRUfRwY9C5WfTrLSDXbwn/SyqfLA7KI4ZNreBjELJoZycH6CEeLKTryMZJ8k1nFUk8o5HqBGElcuwprNEguBzDDt6h/B/lBUfDkdoeZXj+zknoeBVilh397E2ZVdXPRguWmAQ4SGR0Z96h83CWpZTR7ufhNIY=
  - secure: VylCeIt+tLda8Reran5ffW2awfIZM397ea+lmM4DF/9QRq1i4c5HV5K8/pr9lf2N0/1lisI3Uc92YLKtbRCbGRtfRFGyGDcI+Zx9x3CMeLCOk5q5p0Vf4HerYSLWNF1Oua6uSCmna2+dWO5924tyatrY+TBJtW5NY9oqbjb3nRC/m3Av0bMyBe14uCsd027p6Zm5DNk9tngS1lJKulMrLYt9tLFdE2jOm4XvPTIl1oNs5tAKYh+s7pkafS61a4Oq8DtLtFKydBfM4TyEkepV+Cm0//JFfWO0zomXp+OQaFzFuGMm+SVmuCHPwluQuz264gxJH7BM4HNmOtk6QE3Wc5bEH+HFEQQ9yXfWRhe49v+kJ0Itr/sIqZrJ0WkhNbh2T1XhjFpPez9rXBycHDu2dZYGHwlDuQSmywNXp+OBpsc8Z2e08ubj7BxdBDDQ1aKgddjc/28m5ZFaVsDAgJvN3ams7Y5odqbO6boZ7DsnBZpcwLuoHfhQUiOMCfyrIINWL17MVxrP4GUVuEJwgIGvV33WEIwe+4a537LamzKTjTGQ8hOSGrLQpCRrMkvTHlilDZqHiMNeHmhQYp8UgUiQEbGPZPY0Js2Nwl8zzJs/tGbu7gmIMSYUHszo2JZUzDzZ5w3EJBZpbUY+r0LFEb4l1l9ar4egWxnGu2+xsDKTbhg=
  - secure: U3alp5BQQPHSshbShWvQcEH/s2wd9acm3tDpnp+GfEq+q9KCIhdZQbnOD/IvMJT+CYAwLr4qfGSYaY2vOe79WawiMUrMJB5WElGap3ZRpM1sZ9ooF9IhQuFqtpIzxDzsn/3/pocGWDDgAlZAqkdXqgDhjh4hzhn8Ow0q2LesgjoAel/LD5xHLqW37Q/HEOXfKjA2HyghcT2HBNKRkJQ0pBFo2WSEPOyVlcPg4T9j8Oxpfpye+7iDJU57hVyiiNEpna89M+a+o6+5ToeHcXWg8grjPBxLViZTjFCESOC/zJPk73Z6Ms0ZgyoeZUhh1nwWAvtvjSYGFmOT8wTcsTcmKwc35amgxH3dkV/jGUPGamZWIiQkCkRECu97fEwwu5vg64IIHB3XgKZsaJikiKarqRegJNnlasufChtBW6a5mU8K2KYC14W/4IbhLrPE0zoY3n1yKTCuvyIVS1CNtawaM9bRsz1bn7mxxgrx3NiAH6VVDAR/lUPuy+D/qXSIzRcgy9T27Nr+Ane1PwIvnRXachLaxlD+DPy95sE0mBe5KXIQC6J5oGsMIqAB27QESxFDfuLV8uRAm5qqFkz1xot2uM167bGG/f2befxx/W9/EQ4ikFIqgQQxrbC4oZKOEbWzsjWcfoy7OJwWTuP2OrEvnLCneFt7jcjX6gZlzdUmeVA=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - g++-4.8
before_install:
- export CXX="g++-4.8"
- npm install -g npm@latest
- npm install -g ganache-cli truffle
- npm install -g @cleanunicorn/mythos
install:
- npm install
- npm install truffle-hdwallet-provider
script:
- ganache-cli &
- truffle test
- mythos analyze contracts/BluzelleESR.sol BluzelleESR --mythxEthAddress=MYTHX_ETH_ADDRESS
  --mythxPassword=MYTHX_PASSWORD
- truffle compile
- truffle exec scripts/deploy_test.js --network ropsten
